### ISSUE TITLE
Make some mocked Unit Tests

### ISSUE THREAD

**Issue by lholmquist** [keycloak/keycloak-admin-client#3]
Currently the tests we have are integration tests.  they need to have a keycloak server running for them to pass.

I would like to also have some other tests where the server is mocked, so we can easier manipulate returned error values to get full test coverage

I'll probably split the directories into unit/integration tests while i'm at it

**Comment by helio-frota** [comment]
bucharest-gold/entente#133

**Comment by lholmquist** [comment]
I'm going to close this since we already have integration tests, no need to duplicate things
