### ISSUE TITLE
How set custom email theme (keycloak.admin.client:2.5.1)

### ISSUE THREAD

**Issue by thomasharin** [keycloak/keycloak-admin-client#57]
I wanna make java rest application for using keycloak. I made registration on keycloak with email verification, but email sended to user has bad content. In keycloak admin console I did set email theme for realm to my custom theme. Keycloak.admin.client using some own settings for theme? How I set content of email send by keycloak.admin.client method sendVerifyEmail().

```
(RealmResource realmResource = (getKeycloakInstance().realm(userRealm));
UsersResource usersResource = realmResource.users();
usersResource.get(userID).sendVerifyEmail(); 

private Keycloak getKeycloakInstance(){     
        Keycloak kc = KeycloakBuilder.builder()
                .serverUrl("http://" + keycloakDNS + ":8080/auth")
                .realm(adminRealm)
                .username(adminUsername)
                .password(adminPassword)
                .clientId("admin-cli")
                .resteasyClient(new ResteasyClientBuilder().connectionPoolSize(10).build())
                .build();
        LOG.info("Keycloak instance created for admin "+adminUsername+".");
        return kc;
    })
```

This is my settings for using realm in keycloak admin console, if can it help.

![keycloak theme setting](https://user-images.githubusercontent.com/22837519/30198328-684f7a56-946d-11e7-9545-7c8994ac3c11.png)

**Comment by lholmquist** [comment]
This is the node.js client, not the java client.

i would create a JIRA with your issue,  https://issues.jboss.org/projects/KEYCLOAK

**Comment by thomasharin** [comment]
I know @lholmquist , that admin console is not java client, but when I change something and click on "save", then the admin console send request to my keycloak server with configuration. In configuration I see attributes for theme definition. So I don't understand is email theme set for realm or just for client? If for client how can I set custom email theme for java client?

**Comment by maximRNBack** [comment]
To my understanding themes settings are realm-level settings.
Not sure I understand what you're trying to do.

The issue header was "How set custom email theme", so if anyone is trying to use the node.js admin client to change a theme, this should work:

```javascript
const realmName = 'my_realm';
const themeName = 'my_theme';
keycloakAdminClient(settings)
  .then((client) => {
    client.realms.find(realmName)
      .then((realm) => {
        realm.emailTheme = themeName;
        return client.realms.update(realmName, realm);
      }).then(() => console.log('success')).catch(err => console.log('err1:', err));
  }).catch(err => console.log('err2:', err));
```

**Comment by macalak** [comment]
Hi, what we are looking for, is to activate verification e-mail delivery using Keycloak API (sendVerifyEmail). We have our customized e-mail template in theme configured for our realm, but Keycloak uses the e-mail template from the default theme on sendVerifyEmail invocation. Interesting is, that during the user registration flow, the e-mail template from our customized theme is used. Do we miss something? Thanks, Ivan.

**Comment by maximRNBack** [comment]
Sounds like a bug or a missing configuration. I don't know.
Either way it's not related to this repository.
I guess @lholmquist is right. Open an issue in keycloak's `JIRA`.
:)

**Comment by thomasharin** [comment]
Besides that. it's possible to set custom URL for links in sended email? In java application for create keycloak instance we use dns name in rancher of our keycloak, so when I call sendVerifyEmail() from application, confirm link have in address this dns name intead our keycloak URL. Is possible set this?

This link is in email when I register user from http://myKeycloak/auth

     https://myKeycloak/auth/realms/parkingrealm/login-actions/email-verification?code=O3tir5kbrrlM2vSAVyJRcMyW0S7zQbgICIgCV6izW9M.8ad3ba39-0ca9-49ce-8f4e-46c924d9e465&key=wey3E2rTLb


And this is when I send verify email from java application wit sendVerifyEmail() method

     https://keycloak.keycloak-postgres:8080/auth/realms/parkingrealm/login-actions/execute-actions?key=14_AfxUEjD_G6PhrgaTkLwZFgolaKdYX1WDc5D3qIeU.5b100452-fd65-4479-9fa6-fcb1457e3e43

**Comment by stianst** [comment]
This library is no longer being maintained, please use https://github.com/keycloak/keycloak-nodejs-admin-client instead
