### ISSUE TITLE
Can't create composite roles

### ISSUE THREAD

**Issue by c3s4r** [keycloak/keycloak-admin-client#78]
I'm trying to create a composite role. Looking at the code I see you are calling this endpoint: `${client.baseUrl}/admin/realms/${realm}/clients/${id}/role`

Looking at the Keycloak API documentation for [creating a new role](http://www.keycloak.org/docs-api/3.4/rest-api/index.html#_createrole), (the endpoint you are using), it states that I should send a [RoleRepresentation](http://www.keycloak.org/docs-api/3.4/rest-api/index.html#_rolerepresentation), which can contain [RoleRepresentation-Composites](http://www.keycloak.org/docs-api/3.4/rest-api/index.html#_rolerepresentation-composites).

The documentation is not clear enough if I should send ids or names of clients and ids or names of roles. It doesn't matter what I send, it creates the role, but without the composites.

In the keycloak admin console I see that they call a different endpoint for adding "composites", after the role has been created.

Is this an issue in the documentation? Is it a bug in keycloak?

The problem is there's no way to add a composite using this library. Or am I missing something?

**Comment by mstruk** [comment]
The way Admin Console does it is how it should be done. Other approaches
won't work. Creating a role is one operation.

Adding roles to another role is a different operation even though it uses
the same RoleRepresentation to pass information.

**Comment by imranshafqat** [comment]
@c3s4r Have you found out how to create composite roles?

**Comment by c3s4r** [comment]
I think the only way is to do it in two operations, just as the admin console does. (See the answer by @mstruk)
