### ISSUE TITLE
Tests failing with keycloak-3.4.3.Final

### ISSUE THREAD

**Issue by nikolaymihaylov** [keycloak/keycloak-admin-client#79]
Hello,

I was trying to create some pull requests following [this process](https://github.com/keycloak/keycloak-admin-client/blob/master/CONTRIBUTING.md). More specifically, I tried running the following:
```
./scripts/start-server.sh
make
```
This downloaded version `keycloak-3.4.3.Final` for me.

However, some of the existing tests fail:
```
 Failed Tests: There were 3 failures

    Test getting a client's roles

      ✖ Should return 14 roles


    Test getting the list of Realms

      ✖ The realm should be named master


    Test getting the number of users in a Realm

      ✖ [object Object]

  total:     124
  passing:   121
  failing:   3
```

Running `make` again, even more tests fail:
```
  total:     71
  passing:   6
  failing:   65
```
where the error is usually:
```
 ✖ [object Object]
    ------------------
      operator: error
      expected: |-
        undefined
      actual: |-
        { error: 'invalid_grant', error_description: 'Invalid user credentials' }
      at: process._tickCallback (internal/process/next_tick.js:160:7)
```

# Questions
- Do the tests need to be updated to work with newer Keycloak versions or am I doing something wrong?
- Are there any ongoing efforts to get them updated?
- It seems that this problem has existed at least since version 3.2.0.Final (as reported in #52) but there have been some commits to `master` branch since then. How come? Do the tests pass for some people?

**Comment by clkao** [comment]
The "Test getting the list of Realms" seems to be caused by the realms endpoint not returning realms in the order listed and created by `scripts/kc-setup-for-tests.json`.  not sure if that's part of the api spec that keycloak guarantees?

**Comment by stianst** [comment]
This library is no longer being maintained, please use https://github.com/keycloak/keycloak-nodejs-admin-client instead
