### ISSUE TITLE
project status?

### ISSUE THREAD

**Issue by clkao** [keycloak/keycloak-admin-client#81]
Hi, there are quite a few PR queued up. what can we do to get them moving?

Do we currently have active maintainers? and do we need more reviewers?

**Comment by karlhorky** [comment]
cc @lholmquist @helio-frota

Would you be ok with the community taking over some of the maintenance work from you?

For example, giving some people maintainer status? Like for instance, multiple-time contributors:

- @clkao
- @DrakkenSaer
- @jderuere

Or owners of forks:

- @javadababadoo or @juansmolano ([NebulaEngineering fork](https://github.com/NebulaEngineering/keycloak-admin-client))

Thanks for all your work on this project!

**Comment by helio-frota** [comment]
> Would you be ok with the community taking over some of the maintenance work from you?

That's fine with me, but the project is no longer part of the github organization I belong to.
So, I do not know how the governance / product works with the keycloak project.

I think that @stianst and/or @abstractj can better clarify.

**Comment by karlhorky** [comment]
It does look like there's another module from @wwwy3y3 that seems to be better supported and tested (also has Typescript support):

https://github.com/Canner/keycloak-admin

**Comment by clkao** [comment]
Can someone from keycloak project clarify the governance status for the project?  (We basically commissioned Canner for some keycloak related works and they decided to work on a more testable js client library and open source it)

**Comment by stianst** [comment]
Hi, I'm afraid we have never had resources to maintain this project fully. At the moment we haven't opened out for people outside the main Keycloak team to have write access to projects in the Keycloak organization.

If someone is interested in maintaining this project please get in touch with me on email.

In the mean time I see tests on all open PRs are failing. Not sure why. It would help greatly if someone can contribute fixes to the tests so we can start seeing green lights. After that we will try to review and get PRs merged.

**Comment by karlhorky** [comment]
Thanks for the answer @stianst! Cool that you're open to have some help from the community :)

**Comment by karlhorky** [comment]
Crazy thought - if @Canner would also be fine with this, what about merging `keycloak-admin-client` and `keycloak-admin`?

The `keycloak-admin` project has [lots of tests](https://github.com/Canner/keycloak-admin/tree/master/test) and [functionality](https://github.com/Canner/keycloak-admin#supported-apis) that this project does not, as well as an improved API.

This could be done via a major version bump.

cc @wwwy3y3 @stianst @abstractj

**Comment by stianst** [comment]
An alternative that may be better is that we deprecate this project completely and just refer to https://github.com/Canner/keycloak-admin instead. That is usually what we do for fully community maintained bits. We can list it on https://www.keycloak.org/extensions.html together with other community maintained extensions.

**Comment by karlhorky** [comment]
> deprecate this project completely and just refer to https://github.com/Canner/keycloak-admin instead

Hm, I see. I was hoping for a merge instead because:

- better conservation of the existing energy and maintainers of this project
- increased visibility under the `keycloak` organization (not just a link elsewhere)
- less confusion and redirection
- possible future potential for Red Hat support

But I can understand that other reasons may outweigh these for your decision.

**Comment by karlhorky** [comment]
Cheers, I'll see if I can ping @Canner on this.

**Comment by wwwy3y3** [comment]
Hi @stianst @karlhorky 

Thanks for the mention!

For now, we prefer simply adding a reference link to `keycloak-admin` in readme because `keycloak-admin` is currently under active development and maintenance and it might be harder for us to contribute if the repo is not under our full control.

**Comment by stianst** [comment]
@wwwy3y3 great that you are on-board with the idea. I need to have some discussions internally, but we would love to see this happen as we've long wanted to open up for outside maintainers of some things in the Keycloak family. I'll get back to you next week, then let's make sure we talk through it all before we go ahead with the merge.

**Comment by wwwy3y3** [comment]
@stianst Hi, just curious about how the discussion goes.

**Comment by stianst** [comment]
@wwwy3y3 We'd like to go ahead with it. A few things left to discuss are exactly how we list maintainers of repositories, including company names/logos. Not sure the readme is the correct place, we may want a separate file (maintainers.md). I don't have any objections to a small logo at the end of the readme to mention where it came from initially, as long as you are open to that maybe being removed in the future (don't worry, I don't have any plans to remove it, just in case there is some reasons that pops up in the future).

Other things is best approach to do the move. Does your library have everything this library has? Is the APIs compatible? Or is there a straightforward migration path? What's the easiest way to move it. Should just do a single commit deleting everything that's here and replacing with yours? At least for now I think it'll be better if you're responsible for making releases, but some point in the future we may want to coordinate releasing it together with the rest of Keycloak.

**Comment by wwwy3y3** [comment]
hi @stianst sorry for the late response. I'm okay with a separated maintainer file and just a small logo at the bottom of the readme.

As approaches to do the move, since I would like to keep my commits, I'm thinking we can simply git force push to override all the commits here.

As the API coverage, last time I checked, `keycloak-admin` covered all the APIs this module has covered, so it shouldn't be a problem.

**Comment by karlhorky** [comment]
> since I would like to keep my commits, I'm thinking we can simply git force push to override all the commits here

Maybe we can keep both commit histories? It may be useful to have the source code of the old client as a reference in the history. Maybe something else to consider would be to even keep the original client archived somewhere in the repo.

I have done a similar merge of two repositories in the past. If I remember correctly it went something like this:

https://thoughts.t37.net/merging-2-different-git-repositories-without-losing-your-history-de7a06bba804

**Comment by wwwy3y3** [comment]
@karlhorky @stianst Maybe we can rename and archive this repo in order to keep the code and commits as a reference.

Then, we create a new repo to push the `keycloak-admin`.

**Comment by karlhorky** [comment]
> Maybe we can rename and archive this repo in order to keep the code and commits as a reference.

Would be one way to do it, but I mentioned a couple of points that would be potentially better with a more standard 2-repo merge: https://github.com/keycloak/keycloak-admin-client/issues/81#issuecomment-424300074

**Comment by stianst** [comment]
Folks, sorry for the lack of responses from me. We are rather busy at the moment on wrapping-up Keycloak 4.x (and RH-SSO releases). I'd love to get back to this in January 2019, is that OK with everyone?

**Comment by stianst** [comment]
Sorry for the lack of response here. We've finally got around to discussing this and we would like to move forwards with the following plans:

* Archive keycloak/keycloak-admin repository
* Move Canner/keycloak-admin to keycloak/keycloak-nodejs-admin-client
* Use GitHub issues for reporting issues, as it makes little sense to have this in JIRA
* Add MAINTAINERS.MD file. I'd like one person to be the lead for the component as well as a list of people that are considered maintainers. At the bottom of the MAINTAINERS.MD file I'm happy with adding a statement that this project came from Canner including a small company logo
* Maintainers of the component should setup CI separate to ours to run tests on PRs
* Maintainers of the component are responsible for issues as well as review and merge of community PRs
* Maintainers of the component are responsible for testing and releasing the component. For releases I would clearly state a mapping between the component version and the Keycloak releases.

If everyone is happy with that I'd like to send an email to Keycloak dev and user mailing lists and give it a week for comments before going ahead with the above plans

**Comment by zagaria** [comment]
Hello. 

It looks like good, but have one question: 

1. How to solve the problem (or it's not a problem?) with the license? 

For https://github.com/Canner/keycloak-admin/blob/master/package.json is ISC license. 

This license has a small issue http://www.gnu.org/licenses/license-list.html#ISC. Or possible re-license under Apache license?

**Comment by stianst** [comment]
That's a good point. I don't know much about the ISC license. It could be re-licenses as part of the move, or perhaps dual licenses.

**Comment by zagaria** [comment]
@wwwy3y3 please take a look

**Comment by wwwy3y3** [comment]
Hi @zagaria @stianst Sorry for the late response.

The license could definitely be re-license to Apache license.

As for the plans suggested by @stianst, it looks good to me.

If given permission to the new repo, I'd be happy to follow the plans and set up the repo initially. 

As for the maintainers, maybe @karlhorky @zagaria or other people from keycloak team might be interested to maintain it with Canner?

Thanks!

**Comment by stianst** [comment]
@wwwy3y3 temporarily added you to the Keycloak organization so you can create a new repository in http://github.com/keycloak. Please go ahead and move Canner/keycloak-admin to keycloak/keycloak-nodejs-admin-client (it is ideal to move rather than create new repo as that gives the full history, issues and also makes it more visible to anyone already interested in the existing repo).

**Comment by karlhorky** [comment]
@wwwy3y3 I think @amazeeio may have some interest in co-maintainer status, but since I'm not currently working on this project, I would pass the reins to @rocketeerbkw and/or @Schnitzel.

**Comment by zagaria** [comment]
@wwwy3y3 for me, it's interesting to maintain. I actively work with KeyCloak product and using KeyCloak REST API. If the license will Apache 2.0 - it's great because for me it was the only reason why I still work with the old keycloak-admin-client.

**Comment by Schnitzel** [comment]
Hi from @amazeeio 
As we are using this actively within https://github.com/amazeeio/lagoon we could definitely help and contribute some stuff back. We couldn't do a full maintainership though, just too much going on and want to prevent any sad situations :)

**Comment by stianst** [comment]
Thanks everyone. 

This repository is now being archived and we recommend everyone to switch to the new library at https://github.com/keycloak/keycloak-nodejs-admin-client
