### ISSUE TITLE
How to use keycloak admin client in a maven java project with Spring boot -Security

### ISSUE THREAD

**Issue by william1795** [keycloak/keycloak-admin-client#87]
Hello every body, **please somebody can help me?** i would like to know how can i correctly use a keycloak admin client in a maven project with spring boot - security.
**I'm interest to how to create an user, assigned or remove role, get token when user is authenticated.**
Currently i have try it but i received only errors like **"401 unauthorised" or "400 Bad request"**

Examples : 

         Keycloak keycloak = KeycloakBuilder.builder()
				.serverUrl("http://localhost:8180/auth")
				.realm("RealmName")
				.username("admin")
				.password("admin")
				.clientId("MyClient")
				.clientSecret(clientSecret).grantType("password")
				.resteasyClient(new ResteasyClientBuilder()
						.connectionPoolSize(10).build()
				).build();

	    System.out.println(keycloak.tokenManager().getAccessTokenString());

Thanksful!!!

**I use keycloak 4.4.0
spring boot with spring security
eclipse**

**Comment by stianst** [comment]
This is not a support forum and it's also the Node.js admin client library, which has nothing to do with the Java library. Please send questions to user mailing list.
